baseURL = 'https://example.org/'
languageCode = 'zh-cn'
title = '理理斯的书斋'
theme = 'paperMod'

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
showToc = true
showReadingTime = false
showShareButtons = false
enableSearch = true

[menus]
  [[menus.main]]
    name = "分类"
    url = "/categories/"
    weight = 1

[params.homeInfoParams]
Title = "理理斯"
content = "财务小兵📔 | 热爱胡思乱想"

[params.profileMode]
enabled = false
title = "理理斯"
subtitle = "财务小兵，热爱胡思乱想"

[[params.socialIcons]]
name = "github"
url = "https://github.com/llt003"
